language: R

sudo: required

r_packages:
  - covr

apt_packages:
  - r-cran-rjags

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    rooms:
      - audrey.beliveau@uwaterloo.ca
    on_success: change
    on_failure: always